### ISSUE TITLE
why not backprop during the training

### ISSUE THREAD

**Issue by nebyu08** [rasbt/faster-pytorch-blog#8]
i noticed that you are torch no grad in the training step function and not using it in the validation and testing part why are we using it in the training step since the model is going to back prop during the training

**Comment by rasbt** [comment]
Good point. That's because the `Trainer` already takes care of it for the `validation_step` and `test_step`. It doesn't do that for the `training_step` because that's where/how you usually train the model, so that's why I was adding it for that evaluation subsection manually. Good question actually!
